server:
  port: 8081

spring:
  profiles:
    active: local

feign:
  client:
    config:
      default:
        logger-level: full
        connect-timeout: 5000
        read-timeout: 5000

slack:
  webhook-url: slack url μ„Έν…..

book:
  reserve-topic: book.reservation

---
spring:
  config:
    activate:
      on-profile: local






